workspace: "" # Path to the workspace

Log:
  level: "info" # Log level (debug, info, warning, error, critical), default is ""
  format: "" # Log format, default is "%(asctime)s\t%(name)s\t%(levelname)s\t[%(filename)s:%(funcName)s:%(lineno)d]\t%(message)s"

Token:
  GITHUB: "" # GitHub token for accessing private repositories
  SKILLS_MP: "" # Skills Marketplace token

Check:
  check_method:
    - "security_scan"
    - "llm_gurad"
